// Generated by LiveScript 1.2.0
(function(){
  var rek, requires;
  rek = require('rekuire');
  requires = rek('requires');
  module.exports = {
    MarshalMw: requires.file('marshaller-mw')
  };
}).call(this);
