// Generated by LiveScript 1.2.0
(function(){
  var Class;
  Class = require('jsclass/src/core').Class;
  module.exports = new Class({
    initialize: function(obj){
      return _.keys(obj).each(function(key){
        return this[key] = obj[key];
      });
    }
  });
}).call(this);
