// Generated by LiveScript 1.2.0
(function(){
  var requires, _, Class, BaseModel, Person;
  requires = require('../../../requires');
  _ = require('prelude-ls');
  Class = require('jsclass/src/core').Class;
  BaseModel = requires.clazz('base_model');
  Person = new Class(BaseModel, {
    initialize: function(obj){
      return this.callSuper();
    },
    fullName: function(){
      return [this.firsName, this.lastName].join(' ');
    }
  });
  module.exports = Person;
}).call(this);
