// Generated by LiveScript 1.2.0
(function(){
  var rek, requires, _, Class, BaseModel;
  rek = require('rekuire');
  requires = rek('requires');
  _ = require('prelude-ls');
  Class = require('jsclass/src/core').Class;
  BaseModel = requires.clazz('base_model');
  module.exports = new Class(BaseModel, {
    initialize: function(obj){
      return this.callSuper();
    },
    fullName: function(){
      return [this.firsName, this.lastName].join(' ');
    }
  });
}).call(this);
