// Generated by LiveScript 1.2.0
(function(){
  var Class, Encrypter, Marshaller, slice$ = [].slice;
  Class = require('jsclass/src/core').Class;
  Encrypter = requires.util('encrypter');
  Marshaller = new Class({
    deleteProperties: function(){
      var names;
      names = slice$.call(arguments);
      return names.flatten.compact.each(function(name){
        var ref$, ref1$;
        return ref1$ = (ref$ = this.data)[name], delete ref$[name], ref1$;
      });
    },
    encrypt: function(value){
      return this.encrypter.encrypt(value);
    },
    encrypter: function(){
      return new Encrypter;
    }
  });
  module.exports = Marshaller;
}).call(this);
