// Generated by LiveScript 1.2.0
(function(){
  var loadMwStack, app, person, decoratedPerson, storeMwStack, modelMw, ModelMw, ModelRunner, Middleware;
  loadMwStack = new Middleware('model').use({
    decorate: DecoratorMw
  });
  app = {
    decorators: new ContextDecorators
  };
  app.decorators.set('person', Person);
  person = {
    name: 'Joe 6 Pack',
    age: 28,
    clazz: 'person'
  };
  loadMwStack = new Middleware('model').use(DecorateMw);
  decoratedPerson = loadMwStack.run(person);
  storeMwStack = new Middleware('model').use(MarshalMw);
  storeMwStack.run(decoratedPerson);
  modelMw = requires.file('index');
  ModelMw = modelMw.mw;
  ModelRunner = modelMw.runner;
  Middleware = require('middleware').Middleware;
}).call(this);
