// Generated by LiveScript 1.2.0
(function(){
  var Person, DecorateMw, loadMwStack, app, person, decoratedPerson;
  Person = require('person');
  DecorateMw = require('decorate-mw');
  loadMwStack = new Middleware('model').use({
    decorate: DecorateMw
  });
  app || (app = {});
  app.decorators.register('person', Person);
  person = {
    name: 'Joe 6 Pack'
  };
  ({
    age: 28,
    clazz: 'person'
  });
  decoratedPerson = loadMwStack.run(person);
}).call(this);
