// Generated by LiveScript 1.2.0
(function(){
  var Class, Encrypter;
  Class = require('jsclass/src/core').Class;
  Encrypter = new Class({
    encrypt: function(data){
      return "x-" + data + "-x";
    }
  });
  module.exports = Encrypter;
}).call(this);
