// Generated by LiveScript 1.2.0
(function(){
  var Class, requires, Marshaller, PersonMarshaller;
  Class = require('jsclass/src/core').Class;
  requires = require('../../../requires');
  Marshaller = requires.lib('marshaller');
  PersonMarshaller = new Class(Marshaller, {
    marshal: function(data){
      this.callSuper();
      if (this.data.password != null) {
        this.data.password = this.encrypt(this.data.password);
      }
      delete this.data.status;
      this.deleteProperties('age', 'status');
      return this.data;
    }
  });
  module.exports = PersonMarshaller;
}).call(this);
