// Generated by LiveScript 1.2.0
(function(){
  var requires;
  requires = require('../../requires');
  requires.clazz('person');
  module.exports = {
    person: classes[function(data){
      return new Person(data);
    }]
  };
}).call(this);
