// Generated by LiveScript 1.2.0
(function(){
  var requires;
  requires = require('../../requires');
  requires.marshaller('person');
  module.exports = {
    person: function(data){
      return new PersonMarshaller(data);
    }
  };
}).call(this);
